In [87]:
import numpy as np

X="ABCBDAB"
Y="BDCABA"
def LCS_LENGTH(X,Y):
    m= len(X)
    n= len(Y)
    c=[[0]*(n+1) for i in range(m+1)]
    b=[[None]*(n+1) for i in range(m+1)]
    #print(c)
    #print()
    for i in range(1,m+1):
        for j in range(1,n+1):
            if X[i-1]==Y[j-1]:
                c[i][j]=c[i-1][j-1]+1
                #print(f"*{X[i-1]}")
                b[i][j]="`" # Upper Left
            elif c[i-1][j]>=c[i][j-1]:
                c[i][j]=c[i-1][j]
                b[i][j]="^"
            else:
                c[i][j]=c[i][j-1]
                b[i][j]="L"
    return c,b


In [88]:
X="ABCBDAB"
Y="BDCABA"
c,b=LCS_LENGTH(X,Y)


In [89]:
#By Using Table b
def PRINT_LCS(b,X,i,j):
    if i==0 or j==0:
        return
    if b[i][j]=="UL":
        PRINT_LCS(b,X,i-1,j-1)
        print(X[i-1])
    elif b[i][j]=="U":
        PRINT_LCS(b,X,i-1,j)
    else:
        PRINT_LCS(b,X,i,j-1)


In [90]:
#Without 
def PRINT_LCS(c,X,Y,i,j):
    if i==0 or j==0:
        return
    if X[i-1]==Y[j-1]: #UL
        PRINT_LCS(c,X,Y,i-1,j-1)
        print(X[i-1])
    else:
        if c[i-1][j] >= c[i][j-1]:#UP
            PRINT_LCS(c,X,Y,i-1,j)   
        else:  #Left
            PRINT_LCS(c,X,Y,i,j-1)
          


In [91]:
print(c)
print(b)

[[0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 1], [0, 1, 1, 1, 1, 2, 2], [0, 1, 1, 2, 2, 2, 2], [0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 2, 2, 3, 3], [0, 1, 2, 2, 3, 3, 4], [0, 1, 2, 2, 3, 4, 4]]
[[None, None, None, None, None, None, None], [None, '^', '^', '^', '`', 'L', '`'], [None, '`', 'L', 'L', '^', '`', 'L'], [None, '^', '^', '`', 'L', '^', '^'], [None, '`', '^', '^', '^', '`', 'L'], [None, '^', '`', '^', '^', '^', '^'], [None, '^', '^', '^', '`', '^', '`'], [None, '`', '^', '^', '^', '`', '^']]


In [92]:
PRINT_LCS(c,X,Y,len(X),len(Y))

B
C
B
A


In [93]:
Y

'BDCABA'

In [94]:
c[5][8]

IndexError: list index out of range

In [95]:
b[6]


[None, '^', '^', '^', '`', '^', '`']

In [96]:
X= "10010101"
Y= "010110110"
c,b=LCS_LENGTH(X,Y)


In [48]:
X[5]

'1'

In [97]:
print()
print(np.matrix(LCS_LENGTH(X,Y)[0]))
print(np.matrix(LCS_LENGTH(X,Y)[1]))



[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 3 3 3 3]
 [0 1 2 2 3 3 3 4 4 4]
 [0 1 2 3 3 3 4 4 4 5]
 [0 1 2 3 4 4 4 5 5 5]
 [0 1 2 3 4 4 5 5 5 6]
 [0 1 2 3 4 5 5 6 6 6]]
[[None None None None None None None None None None]
 [None '^' '`' 'L' '`' '`' 'L' '`' '`' 'L']
 [None '`' '^' '`' 'L' 'L' '`' 'L' 'L' '`']
 [None '`' '^' '`' '^' '^' '`' 'L' 'L' '`']
 [None '^' '`' '^' '`' '`' '^' '`' '`' 'L']
 [None '`' '^' '`' '^' '^' '`' '^' '^' '`']
 [None '^' '`' '^' '`' '`' '^' '`' '`' '^']
 [None '`' '^' '`' '^' '^' '`' '^' '^' '`']
 [None '^' '`' '^' '`' '`' '^' '`' '`' '^']]


In [98]:
c_=np.matrix(LCS_LENGTH(X,Y)[0],dtype=object)
b_=np.matrix(LCS_LENGTH(X,Y)[1],dtype=object)




In [99]:

c_[0,1:]=np.matrix(list(Y),dtype=object)
c_[1:,0]=np.matrix(list(X)).T

b_[0,1:]=np.matrix(list(Y))
b_[1:,0]=np.matrix(list(X)).T

In [100]:
print(b_)

print(c_)

[[None '0' '1' '0' '1' '1' '0' '1' '1' '0']
 ['1' '^' '`' 'L' '`' '`' 'L' '`' '`' 'L']
 ['0' '`' '^' '`' 'L' 'L' '`' 'L' 'L' '`']
 ['0' '`' '^' '`' '^' '^' '`' 'L' 'L' '`']
 ['1' '^' '`' '^' '`' '`' '^' '`' '`' 'L']
 ['0' '`' '^' '`' '^' '^' '`' '^' '^' '`']
 ['1' '^' '`' '^' '`' '`' '^' '`' '`' '^']
 ['0' '`' '^' '`' '^' '^' '`' '^' '^' '`']
 ['1' '^' '`' '^' '`' '`' '^' '`' '`' '^']]
[[0 '0' '1' '0' '1' '1' '0' '1' '1' '0']
 ['1' 0 1 1 1 1 1 1 1 1]
 ['0' 1 1 2 2 2 2 2 2 2]
 ['0' 1 1 2 2 2 3 3 3 3]
 ['1' 1 2 2 3 3 3 4 4 4]
 ['0' 1 2 3 3 3 4 4 4 5]
 ['1' 1 2 3 4 4 4 5 5 5]
 ['0' 1 2 3 4 4 5 5 5 6]
 ['1' 1 2 3 4 5 5 6 6 6]]


In [55]:
np.matrix(list(Y),dtype=object) 

matrix([['B', 'D', 'C', 'A', 'B', 'A']], dtype=object)

In [56]:
c[0,1:]


matrix([['B', 'D', 'C', 'A', 'B', 'A']], dtype=object)

In [57]:
c
b

matrix([[None, 'B', 'D', 'C', 'A', 'B', 'A'],
        ['A', '^', '^', '^', '`', '<', '`'],
        ['B', '`', '<', '<', '^', '`', '<'],
        ['C', '^', '^', '`', '<', '^', '^'],
        ['B', '`', '^', '^', '^', '`', '<'],
        ['D', '^', '`', '^', '^', '^', '^'],
        ['A', '^', '^', '^', '`', '^', '`'],
        ['B', '`', '^', '^', '^', '`', '^']], dtype=object)

In [58]:
print(c)
print(b)

[[0 'B' 'D' 'C' 'A' 'B' 'A']
 ['A' 0 0 0 1 1 1]
 ['B' 1 1 1 1 2 2]
 ['C' 1 1 2 2 2 2]
 ['B' 1 1 2 2 3 3]
 ['D' 1 2 2 2 3 3]
 ['A' 1 2 2 3 3 4]
 ['B' 1 2 2 3 4 4]]
[[None 'B' 'D' 'C' 'A' 'B' 'A']
 ['A' '^' '^' '^' '`' '<' '`']
 ['B' '`' '<' '<' '^' '`' '<']
 ['C' '^' '^' '`' '<' '^' '^']
 ['B' '`' '^' '^' '^' '`' '<']
 ['D' '^' '`' '^' '^' '^' '^']
 ['A' '^' '^' '^' '`' '^' '`']
 ['B' '`' '^' '^' '^' '`' '^']]


In [102]:
PRINT_LCS(c,X,Y,len(X),len(Y))

1
0
0
1
1
0


In [85]:
X= "10010101"
Y= "010110110"
c,b=LCS_LENGTH(X,Y)


In [13]:
def PRINT_ALL_LCS(c,X,i,j):
    print(f"i,j:{i},{j}")
    if i==0 or j==0:
        return set([""])

    if c[i][j] == c[i][j-1] or c[i][j]==c[i-1][j]:
        if c[i][j] == c[i-1][j]:#UP 
            U.update(PRINT_ALL_LCS(c,X,i-1,j))
    
        if c[i][j]==c[i][j-1]:#Left
            U.update(PRINT_ALL_LCS(c,X,i,j-1))
        return U
    else:#UL
        return set([Z+X[i-1] for Z in PRINT_ALL_LCS(c,X,i-1,j-1)])
        

In [114]:
def PRINT_ALL_LCS(c,X,Y,i,j):
    if i==0 or j==0:
        return set([""])
    if X[i-1]==Y[j-1]: #UL
        return set([Z+X[i-1] for Z in PRINT_ALL_LCS(c,X,Y,i-1,j-1)])
    else:
        U=set()

        if c[i-1][j] >= c[i][j-1]:#UP
            U.update(PRINT_ALL_LCS(c,X,Y,i-1,j))
        if c[i][j-1] >= c[i-1][j]:  #Left
            U.update(PRINT_ALL_LCS(c,X,Y,i,j-1))
        return U          


In [115]:
x=PRINT_ALL_LCS(c,X,Y,len(X),len(Y))

In [116]:
x

{'001010',
 '001011',
 '001101',
 '010101',
 '100110',
 '101010',
 '101011',
 '101101'}

In [107]:
len(Y)

9

In [18]:
PRINT_LCS(c,X,len(X),len(Y))

1
0
1
0
1
0


In [58]:
def backTrackAll(C, X, Y, i, j):
    if i == 0 or j == 0:
        return set([""])
    elif X[i-1] == Y[j-1]:
        return set([Z + X[i-1] for Z in backTrackAll(C, X, Y, i-1, j-1)])
    else:
        R = set()
        if C[i][j-1] >= C[i-1][j]:
            R.update(backTrackAll(C, X, Y, i, j-1))
        if C[i-1][j] >= C[i][j-1]:
            R.update(backTrackAll(C, X, Y, i-1, j))
        return R
backTrackAll(c,X,Y,len(X),len(Y)) 

{'001010',
 '001011',
 '001101',
 '010101',
 '100110',
 '101010',
 '101011',
 '101101'}